### ISSUE TITLE
Crash when getting resources from inside of wizard model

### ISSUE THREAD

**Issue by heinrichreimer** [romannurik/Android-WizardPager#10]
It would be great (and as the guidlnes say "a good practice") if you provide an implementation, that uses android resources instead of fixed text.

This are my thoughts on that:

``` java
package com.example.android.wizardpager;

import com.example.android.wizardpager.wizard.model.AbstractWizardModel;
import com.example.android.wizardpager.wizard.model.BranchPage;
import com.example.android.wizardpager.wizard.model.CustomerInfoPage;
import com.example.android.wizardpager.wizard.model.MultipleFixedChoicePage;
import com.example.android.wizardpager.wizard.model.PageList;

import android.content.Context;

public class SandwichWizardModel extends AbstractWizardModel {
    public SandwichWizardModel(Context context) {
        super(context);
    }

    @Override
    protected PageList onNewRootPageList() {
        return new PageList(
                new BranchPage(this, mContext.getString(R.string.order_type))
                        .addBranch(mContext.getString(R.string.sandwich),
                                new MultipleFixedChoicePage(this, mContext.getString(R.string.meats))
                                        .setChoices(
                                                mContext.getString(R.string.peperoni),
                                                mContext.getString(R.string.turkey),
                                                mContext.getString(R.string.ham),
                                                mContext.getString(R.string.pastrami),
                                                mContext.getString(R.string.roast_beef),
                                                mContext.getString(R.string.bologna)),

                new CustomerInfoPage(this, mContext.getString(R.string.your_info))
                        .setRequired(true)
        );
    }
}
```

Only problem: The wizard model is created before activity's `onCreate()` method and therefore cant access android resources directly.

**Comment by jacklt** [comment]
In `MainActivity` move new instance in method `onCreate`

    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mWizardModel = new SandwichWizardModel(this);
        // ...
    }

In `AbstractWizardModel` add method `getString` (for more readability)

    public String getString(@StringRes int resId) {
        return mContext.getString(resId);
    }

In `SandwichWizardModel ` use `getString(resId)`

    @Override
    protected PageList onNewRootPageList() {
        return new PageList(
                new BranchPage(this, getString(R.string.order_type))
                        .addBranch(getString(R.string.sandwich),
                                new MultipleFixedChoicePage(this, getString(R.string.meats))
                                        .setChoices(
                                                getString(R.string.peperoni),
                                                getString(R.string.turkey),
                                                getString(R.string.ham),
                                                getString(R.string.pastrami),
                                                getString(R.string.roast_beef),
                                                getString(R.string.bologna)),

                new CustomerInfoPage(this, getString(R.string.your_info))
                        .setRequired(true)
        );
    }

HINT: Add gradle dependencies for useful annotation: `@NonNull` `@Nullable` `@StringRes` `@IdRes` ...

    dependencies {
        compile 'com.android.support:support-annotations:21.0.3'
    }

**Comment by achavhan** [comment]
it was helpful thank you

**Comment by brookman-holmes** [comment]
Doing that causes the app to crash on rotate with a null pointer exception because mWizardModel becomes null on rotation
