### ISSUE TITLE
Material design upgrade

### ISSUE THREAD

**Issue by mkosik** [romannurik/Android-WizardPager#20]
How this concept should look in material design fashion (backwards compatible with appcompat)?

In case of prev and next buttons, instead of:

```
android:background="@drawable/selectable_item_background" 
```

this style should be used, right?

```
style="?android:buttonBarButtonStyle"
```

and what about in v21 - there are more BarButtonStyles - neutral, negative, positive?

btw, I saw using material design bar buttons style on Android 4.4.4 in case of Google Now:
![screenshot_2015-01-21-15-27-36](https://cloud.githubusercontent.com/assets/2512454/5848181/ff47eb74-a1d5-11e4-882e-01a99e928a04.png)
Should developers try to "mimic" Android L bar buttons style in their "materialized" apps on pre-Android L devices, the same way as Google Now does? Or is there any way to achieve it thru appcomat v21?

And what about other used elements like StepPagerStrip? Other styling, fonts, dimens, ...?
THX in advance @romannurik :)

**Comment by MarkOSullivan94** [comment]
Hi @mkosik I've got a fork of Roman's wizard which uses a Material Design if you haven't already seen it.

**Comment by MarkOSullivan94** [comment]
@mkosik I've recently issued a pull request for fork of this project which includes Material Design for both Lollipop devices and pre-Lollipop devices.
