### ISSUE TITLE
How to Reset Wizard Model after Data is Sending

### ISSUE THREAD

**Issue by brayanL** [romannurik/Android-WizardPager#33]
Hi bro, your work is awesome, I have a problem, I don't Know How to Reset WizardModel after the Data Sent in Review. The Class AbstractWizardModel
![wizard1](https://cloud.githubusercontent.com/assets/8359783/21825666/a41421be-d752-11e6-8046-c4b229a3e589.png)
In the Line ´AbstractWizardModel.mRootPageList.clear();´ Clean the list Pages and tha Bundle Info, but the Pages are still visible in the wizard.
Please Help me Thanks...! :+1:

**Comment by Dave-Algorism** [comment]
How did u get registerVictimsPresenter.saveVictimdata(mWizardModel.save()); I am trying to save all the data I have in the multistep form to the server. How do I achieve that?

**Comment by imanimulele** [comment]
Hie, I am looking for the same issue, please if someone can help, on how to store all the data in database after completion of steps, thanks

**Comment by najja** [comment]
Any solutions on how to save data to database?

**Comment by imanimulele** [comment]
Hie Najja,
In my main class , i created some code like this,

String text=mWizardModel.findByKey("page key").getData().getString(CustomerInfoPage.Name_Data_Key);,

Page id is found on sandwithmodel as title.
Hope will work for you as it did for me,

**Comment by najja** [comment]
Thank you @imanimulele This has worked perfectly

**Comment by najja** [comment]
@imanimulele ,
multiple selection returns null for that implementation.

How did you deal with that?
