### ISSUE TITLE
question : how to call specific function for example save data when user click next in each page

### ISSUE THREAD

**Issue by yp25** [romannurik/Android-WizardPager#36]
Hi, I have difficulties when try to implement specific function when I click button Next in each page.

For example : I have 3 page : "Registration", "CapturePhoto" ,"Summary"
after user fill some fields in "Registration" page, when user click next button, I want to call "SaveData()" function. This SaveData() function will store text data to web service. 
then after that, "CapturePhoto" page will displayed (and user will take some photo, for example) and when click next button, it will call "SaveData()" function but have different logic with previous page.

I still beginner in Android, 

I tried to modified code in MainActivity - mPager.setOnPageChangeListener, but still confuse. maybe someone will give some guide and help me to solve this. 

Thanks

**Comment by yp25** [comment]
nevermind. I already find solution :)

**Comment by arashifunsho** [comment]
You should have posted how you solved it for others to learn from.... that's how the internet works. Thank you

**Comment by DennisMuchiri** [comment]
please share how you solved
